name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Premake
      if: steps.cache-premake.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz
        tar -xzvf premake-5.0.0-alpha16-linux.tar.gz
        sudo mv premake5 /usr/local/bin/        

    - name: Set Enviroment Variables
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Run Premake
      run: premake5 gmake

    - name: Compile Project (Compiler)
      run: make -f sigma.make config=test CC=clang
      
    - name: Compile Project (Tests)
      run: make -f tests.make config=debug CC=clang

    - name: Run Tests
      run: ./output/tests/bin/Debug/tests run tests ./output/compiler/bin/test/compiler