name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Premake
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz
        tar -xzvf premake-5.0.0-alpha16-linux.tar.gz
        sudo mv premake5 /usr/local/bin/

    - name: Print current dir
      run: ls

    - name: Run Premake
      run: premake5 gmake
      
    - name: Compile Project
      run: make config=debug
