name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Run Premake
      run: .\setup.bat

    - name: Compile Project (Compiler)
      run: msbuild sigma.sln /p:Configuration=Debug /p:Platform="x64"
      
    - name: Compile Project (Tests)
      run: msbuild tests.sln /p:Configuration=Debug /p:Platform="x64"

    - name: Run Tests
      run: output\tests\bin\Debug\tests.exe run tests output\compiler\bin\Debug\compiler.exe
