name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run Premake for Visual Studio
      run: .\setup.bat

    - name: Compile Project with MSBuild
      run: |
        msbuild sigma.sln /p:Configuration=Debug /p:Platform="x64" /p:stdcpp=latest
